//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catagory
    {
        public int c_id { get; set; }
        public string catagory_name { get; set; }
        public string supplier_name { get; set; }
    }
}
