//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int pur_id { get; set; }
        public string purchase_product { get; set; }
        public string purchase_qnty { get; set; }
        public string purchase_price { get; set; }
        public string purchase_amount { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    }
}
