//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenue
    {
        public int id { get; set; }
        public string purchase_amount { get; set; }
        public string sale_amount { get; set; }
        public string revenue1 { get; set; }
    }
}
