//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sa_id { get; set; }
        public string sale_product { get; set; }
        public string sale_qnty { get; set; }
        public string sale_price { get; set; }
        public string sale_amount { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
    }
}
